import random

print("Get the best random password here.")
# total = int(input("enter length of password:\n"))
alpha = int(input("number of characters in password:\n"))
num = int(input("number of numbers in password:\n"))
spe = int(input("number of special characters in password:\n"))


alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
             'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
special = ['!', '@', '#', '$', '%', '&', '*']


# password = ""

# for i in range(1, alpha+1):
#     password += random.choice(alphabets)

# for i in range(1, num+1):
#     password += random.choice(numbers)

# for i in range(1, spe+1):
#     password += random.choice(special)

# print(f"Your random password generated by us is:{password}")

# since the above code generate sequence of alpha first then nums then special
# we need to store the password in list
passwordLIst = []
for i in range(1, alpha+1):
    passwordLIst.append(random.choice(alphabets))

for i in range(1, num+1):
    passwordLIst.append(random.choice(numbers))

for i in range(1, spe+1):
    passwordLIst.append(random.choice(special))

# printing the password from list
random.shuffle(passwordLIst)
password = ""
for i in passwordLIst:
    password += i

print(f"Your random password is:{password}")
